package org.zooper.becuz.restmote.controller.keyboards;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;

import org.zooper.becuz.restmote.controller.PcControllerAbstract;

/**
 * Class used to type characters on the screen 
 * @author bebo
 */
public abstract class Keyboard {

	/**
	 * Map containing special characters
	 */
	public static Map<String, Integer> SPECIAL_CHARS = new HashMap<String, Integer>();
	
	static {
		SPECIAL_CHARS.put("$RES_ENTER" , KeyEvent.VK_ENTER);
		SPECIAL_CHARS.put("$RES_BACK_SPACE" , KeyEvent.VK_BACK_SPACE);
		SPECIAL_CHARS.put("$RES_TAB" , KeyEvent.VK_TAB);
		SPECIAL_CHARS.put("$RES_CANCEL" , KeyEvent.VK_CANCEL);
		SPECIAL_CHARS.put("$RES_CLEAR" , KeyEvent.VK_CLEAR);
		SPECIAL_CHARS.put("$RES_SHIFT" , KeyEvent.VK_SHIFT);
		SPECIAL_CHARS.put("$RES_CONTROL" , KeyEvent.VK_CONTROL);
		SPECIAL_CHARS.put("$RES_ALT" , KeyEvent.VK_ALT);
		SPECIAL_CHARS.put("$RES_PAUSE" , KeyEvent.VK_PAUSE);
		SPECIAL_CHARS.put("$RES_CAPS_LOCK" , KeyEvent.VK_CAPS_LOCK);
		SPECIAL_CHARS.put("$RES_ESCAPE" , KeyEvent.VK_ESCAPE);
		SPECIAL_CHARS.put("$RES_SPACE" , KeyEvent.VK_SPACE);
		SPECIAL_CHARS.put("$RES_PAGE_UP" , KeyEvent.VK_PAGE_UP);
		SPECIAL_CHARS.put("$RES_PAGE_DOWN" , KeyEvent.VK_PAGE_DOWN);
		SPECIAL_CHARS.put("$RES_END" , KeyEvent.VK_END);
		SPECIAL_CHARS.put("$RES_HOME" , KeyEvent.VK_HOME);
		SPECIAL_CHARS.put("$RES_LEFT" , KeyEvent.VK_LEFT);
		SPECIAL_CHARS.put("$RES_UP" , KeyEvent.VK_UP);
		SPECIAL_CHARS.put("$RES_RIGHT" , KeyEvent.VK_RIGHT);
		SPECIAL_CHARS.put("$RES_DOWN" , KeyEvent.VK_DOWN);
		SPECIAL_CHARS.put("$RES_COMMA" , KeyEvent.VK_COMMA);
		SPECIAL_CHARS.put("$RES_MINUS" , KeyEvent.VK_MINUS);
		SPECIAL_CHARS.put("$RES_PERIOD" , KeyEvent.VK_PERIOD);
		SPECIAL_CHARS.put("$RES_SLASH" , KeyEvent.VK_SLASH);
		SPECIAL_CHARS.put("$RES_SEMICOLON" , KeyEvent.VK_SEMICOLON);
		SPECIAL_CHARS.put("$RES_EQUALS" , KeyEvent.VK_EQUALS);
		SPECIAL_CHARS.put("$RES_OPEN_BRACKET" , KeyEvent.VK_OPEN_BRACKET);
		SPECIAL_CHARS.put("$RES_BACK_SLASH" , KeyEvent.VK_BACK_SLASH);
		SPECIAL_CHARS.put("$RES_CLOSE_BRACKET" , KeyEvent.VK_CLOSE_BRACKET);
		SPECIAL_CHARS.put("$RES_NUMPAD0" , KeyEvent.VK_NUMPAD0);
		SPECIAL_CHARS.put("$RES_NUMPAD1" , KeyEvent.VK_NUMPAD1);
		SPECIAL_CHARS.put("$RES_NUMPAD2" , KeyEvent.VK_NUMPAD2);
		SPECIAL_CHARS.put("$RES_NUMPAD3" , KeyEvent.VK_NUMPAD3);
		SPECIAL_CHARS.put("$RES_NUMPAD4" , KeyEvent.VK_NUMPAD4);
		SPECIAL_CHARS.put("$RES_NUMPAD5" , KeyEvent.VK_NUMPAD5);
		SPECIAL_CHARS.put("$RES_NUMPAD6" , KeyEvent.VK_NUMPAD6);
		SPECIAL_CHARS.put("$RES_NUMPAD7" , KeyEvent.VK_NUMPAD7);
		SPECIAL_CHARS.put("$RES_NUMPAD8" , KeyEvent.VK_NUMPAD8);
		SPECIAL_CHARS.put("$RES_NUMPAD9" , KeyEvent.VK_NUMPAD9);
		SPECIAL_CHARS.put("$RES_SEPARATER" , KeyEvent.VK_SEPARATER);
		SPECIAL_CHARS.put("$RES_SEPARATOR" , KeyEvent.VK_SEPARATOR);
		SPECIAL_CHARS.put("$RES_SUBTRACT" , KeyEvent.VK_SUBTRACT);
		SPECIAL_CHARS.put("$RES_DECIMAL" , KeyEvent.VK_DECIMAL);
		SPECIAL_CHARS.put("$RES_DIVIDE" , KeyEvent.VK_DIVIDE);
		SPECIAL_CHARS.put("$RES_DELETE" , KeyEvent.VK_DELETE);
		SPECIAL_CHARS.put("$RES_NUM_LOCK" , KeyEvent.VK_NUM_LOCK);
		SPECIAL_CHARS.put("$RES_SCROLL_LOCK" , KeyEvent.VK_SCROLL_LOCK);
		SPECIAL_CHARS.put("$RES_F1" , KeyEvent.VK_F1);
		SPECIAL_CHARS.put("$RES_F2" , KeyEvent.VK_F2);
		SPECIAL_CHARS.put("$RES_F3" , KeyEvent.VK_F3);
		SPECIAL_CHARS.put("$RES_F4" , KeyEvent.VK_F4);
		SPECIAL_CHARS.put("$RES_F5" , KeyEvent.VK_F5);
		SPECIAL_CHARS.put("$RES_F6" , KeyEvent.VK_F6);
		SPECIAL_CHARS.put("$RES_F7" , KeyEvent.VK_F7);
		SPECIAL_CHARS.put("$RES_F8" , KeyEvent.VK_F8);
		SPECIAL_CHARS.put("$RES_F9" , KeyEvent.VK_F9);
		SPECIAL_CHARS.put("$RES_F10" , KeyEvent.VK_F10);
		SPECIAL_CHARS.put("$RES_F11" , KeyEvent.VK_F11);
		SPECIAL_CHARS.put("$RES_F12" , KeyEvent.VK_F12);
		SPECIAL_CHARS.put("$RES_F13" , KeyEvent.VK_F13);
		SPECIAL_CHARS.put("$RES_F14" , KeyEvent.VK_F14);
		SPECIAL_CHARS.put("$RES_F15" , KeyEvent.VK_F15);
		SPECIAL_CHARS.put("$RES_F16" , KeyEvent.VK_F16);
		SPECIAL_CHARS.put("$RES_F17" , KeyEvent.VK_F17);
		SPECIAL_CHARS.put("$RES_F18" , KeyEvent.VK_F18);
		SPECIAL_CHARS.put("$RES_F19" , KeyEvent.VK_F19);
		SPECIAL_CHARS.put("$RES_F20" , KeyEvent.VK_F20);
		SPECIAL_CHARS.put("$RES_F21" , KeyEvent.VK_F21);
		SPECIAL_CHARS.put("$RES_F22" , KeyEvent.VK_F22);
		SPECIAL_CHARS.put("$RES_F23" , KeyEvent.VK_F23);
		SPECIAL_CHARS.put("$RES_F24" , KeyEvent.VK_F24);
		SPECIAL_CHARS.put("$RES_PRINTSCREEN" , KeyEvent.VK_PRINTSCREEN);
		SPECIAL_CHARS.put("$RES_INSERT" , KeyEvent.VK_INSERT);
		SPECIAL_CHARS.put("$RES_HELP" , KeyEvent.VK_HELP);
		SPECIAL_CHARS.put("$RES_META" , KeyEvent.VK_META);
		SPECIAL_CHARS.put("$RES_BACK_QUOTE" , KeyEvent.VK_BACK_QUOTE);
		SPECIAL_CHARS.put("$RES_QUOTE" , KeyEvent.VK_QUOTE);
		SPECIAL_CHARS.put("$RES_KP_UP" , KeyEvent.VK_KP_UP);
		SPECIAL_CHARS.put("$RES_KP_DOWN" , KeyEvent.VK_KP_DOWN);
		SPECIAL_CHARS.put("$RES_KP_LEFT" , KeyEvent.VK_KP_LEFT);
		SPECIAL_CHARS.put("$RES_KP_RIGHT" , KeyEvent.VK_KP_RIGHT);
		SPECIAL_CHARS.put("$RES_DEAD_GRAVE" , KeyEvent.VK_DEAD_GRAVE);
		SPECIAL_CHARS.put("$RES_DEAD_ACUTE" , KeyEvent.VK_DEAD_ACUTE);
		SPECIAL_CHARS.put("$RES_DEAD_CIRCUMFLEX" , KeyEvent.VK_DEAD_CIRCUMFLEX);
		SPECIAL_CHARS.put("$RES_DEAD_TILDE" , KeyEvent.VK_DEAD_TILDE);
		SPECIAL_CHARS.put("$RES_DEAD_MACRON" , KeyEvent.VK_DEAD_MACRON);
		SPECIAL_CHARS.put("$RES_DEAD_BREVE" , KeyEvent.VK_DEAD_BREVE);
		SPECIAL_CHARS.put("$RES_DEAD_ABOVEDOT" , KeyEvent.VK_DEAD_ABOVEDOT);
		SPECIAL_CHARS.put("$RES_DEAD_DIAERESIS" , KeyEvent.VK_DEAD_DIAERESIS);
		SPECIAL_CHARS.put("$RES_DEAD_ABOVERING" , KeyEvent.VK_DEAD_ABOVERING);
		SPECIAL_CHARS.put("$RES_DEAD_DOUBLEACUTE" , KeyEvent.VK_DEAD_DOUBLEACUTE);
		SPECIAL_CHARS.put("$RES_DEAD_CARON" , KeyEvent.VK_DEAD_CARON);
		SPECIAL_CHARS.put("$RES_DEAD_CEDILLA" , KeyEvent.VK_DEAD_CEDILLA);
		SPECIAL_CHARS.put("$RES_DEAD_OGONEK" , KeyEvent.VK_DEAD_OGONEK);
		SPECIAL_CHARS.put("$RES_DEAD_IOTA" , KeyEvent.VK_DEAD_IOTA);
		SPECIAL_CHARS.put("$RES_DEAD_VOICED_SOUND" , KeyEvent.VK_DEAD_VOICED_SOUND);
		SPECIAL_CHARS.put("$RES_DEAD_SEMIVOICED_SOUND" , KeyEvent.VK_DEAD_SEMIVOICED_SOUND);
		SPECIAL_CHARS.put("$RES_AMPERSAND" , KeyEvent.VK_AMPERSAND);
		SPECIAL_CHARS.put("$RES_ASTERISK" , KeyEvent.VK_ASTERISK);
		SPECIAL_CHARS.put("$RES_QUOTEDBL" , KeyEvent.VK_QUOTEDBL);
		SPECIAL_CHARS.put("$RES_LESS" , KeyEvent.VK_LESS);
		SPECIAL_CHARS.put("$RES_GREATER" , KeyEvent.VK_GREATER);
		SPECIAL_CHARS.put("$RES_BRACELEFT" , KeyEvent.VK_BRACELEFT);
		SPECIAL_CHARS.put("$RES_BRACERIGHT" , KeyEvent.VK_BRACERIGHT);
		SPECIAL_CHARS.put("$RES_AT" , KeyEvent.VK_AT);
		SPECIAL_CHARS.put("$RES_COLON" , KeyEvent.VK_COLON);
		SPECIAL_CHARS.put("$RES_CIRCUMFLEX" , KeyEvent.VK_CIRCUMFLEX);
		SPECIAL_CHARS.put("$RES_DOLLAR" , KeyEvent.VK_DOLLAR);
		SPECIAL_CHARS.put("$RES_EURO_SIGN" , KeyEvent.VK_EURO_SIGN);
		SPECIAL_CHARS.put("$RES_EXCLAMATION_MARK" , KeyEvent.VK_EXCLAMATION_MARK);
		SPECIAL_CHARS.put("$RES_INVERTED_EXCLAMATION_MARK" , KeyEvent.VK_INVERTED_EXCLAMATION_MARK);
		SPECIAL_CHARS.put("$RES_LEFT_PARENTHESIS" , KeyEvent.VK_LEFT_PARENTHESIS);
		SPECIAL_CHARS.put("$RES_NUMBER_SIGN" , KeyEvent.VK_NUMBER_SIGN);
		SPECIAL_CHARS.put("$RES_PLUS" , KeyEvent.VK_PLUS);
		SPECIAL_CHARS.put("$RES_RIGHT_PARENTHESIS" , KeyEvent.VK_RIGHT_PARENTHESIS);
		SPECIAL_CHARS.put("$RES_UNDERSCORE" , KeyEvent.VK_UNDERSCORE);
		SPECIAL_CHARS.put("$RES_WINDOWS" , KeyEvent.VK_WINDOWS);
		SPECIAL_CHARS.put("$RES_CONTEXT_MENU" , KeyEvent.VK_CONTEXT_MENU);
		SPECIAL_CHARS.put("$RES_FINAL" , KeyEvent.VK_FINAL);
		SPECIAL_CHARS.put("$RES_CONVERT" , KeyEvent.VK_CONVERT);
		SPECIAL_CHARS.put("$RES_NONCONVERT" , KeyEvent.VK_NONCONVERT);
		SPECIAL_CHARS.put("$RES_ACCEPT" , KeyEvent.VK_ACCEPT);
		SPECIAL_CHARS.put("$RES_MODECHANGE" , KeyEvent.VK_MODECHANGE);
		SPECIAL_CHARS.put("$RES_KANA" , KeyEvent.VK_KANA);
		SPECIAL_CHARS.put("$RES_KANJI" , KeyEvent.VK_KANJI);
		SPECIAL_CHARS.put("$RES_ALPHANUMERIC" , KeyEvent.VK_ALPHANUMERIC);
		SPECIAL_CHARS.put("$RES_KATAKANA" , KeyEvent.VK_KATAKANA);
		SPECIAL_CHARS.put("$RES_HIRAGANA" , KeyEvent.VK_HIRAGANA);
		SPECIAL_CHARS.put("$RES_FULL_WIDTH" , KeyEvent.VK_FULL_WIDTH);
		SPECIAL_CHARS.put("$RES_HALF_WIDTH" , KeyEvent.VK_HALF_WIDTH);
		SPECIAL_CHARS.put("$RES_ROMAN_CHARACTERS" , KeyEvent.VK_ROMAN_CHARACTERS);
		SPECIAL_CHARS.put("$RES_ALL_CANDIDATES" , KeyEvent.VK_ALL_CANDIDATES);
		SPECIAL_CHARS.put("$RES_PREVIOUS_CANDIDATE" , KeyEvent.VK_PREVIOUS_CANDIDATE);
		SPECIAL_CHARS.put("$RES_CODE_INPUT" , KeyEvent.VK_CODE_INPUT);
		SPECIAL_CHARS.put("$RES_JAPANESE_KATAKANA" , KeyEvent.VK_JAPANESE_KATAKANA);
		SPECIAL_CHARS.put("$RES_JAPANESE_HIRAGANA" , KeyEvent.VK_JAPANESE_HIRAGANA);
		SPECIAL_CHARS.put("$RES_JAPANESE_ROMAN" , KeyEvent.VK_JAPANESE_ROMAN);
		SPECIAL_CHARS.put("$RES_KANA_LOCK" , KeyEvent.VK_KANA_LOCK);
		SPECIAL_CHARS.put("$RES_INPUT_METHOD_ON_OFF" , KeyEvent.VK_INPUT_METHOD_ON_OFF);
		SPECIAL_CHARS.put("$RES_CUT" , KeyEvent.VK_CUT);
		SPECIAL_CHARS.put("$RES_COPY" , KeyEvent.VK_COPY);
		SPECIAL_CHARS.put("$RES_PASTE" , KeyEvent.VK_PASTE);
		SPECIAL_CHARS.put("$RES_UNDO" , KeyEvent.VK_UNDO);
		SPECIAL_CHARS.put("$RES_AGAIN" , KeyEvent.VK_AGAIN);
		SPECIAL_CHARS.put("$RES_FIND" , KeyEvent.VK_FIND);
		SPECIAL_CHARS.put("$RES_PROPS" , KeyEvent.VK_PROPS);
		SPECIAL_CHARS.put("$RES_STOP" , KeyEvent.VK_STOP);
		SPECIAL_CHARS.put("$RES_COMPOSE" , KeyEvent.VK_COMPOSE);
		SPECIAL_CHARS.put("$RES_ALT_GRAPH" , KeyEvent.VK_ALT_GRAPH);
		SPECIAL_CHARS.put("$RES_BEGIN" , KeyEvent.VK_BEGIN);
		SPECIAL_CHARS.put("$RES_UNDEFINED" , KeyEvent.VK_UNDEFINED);
	}
	
	/**
	 * Type the characters on the characters params, if are some special ones defined in {@link #SPECIAL_CHARS}
	 * @param characters
	 * @return true if the characters are handled correctly
	 * @throws Exception 
	 */
	public boolean type(String characters) throws Exception {
		Integer keycode = SPECIAL_CHARS.get(characters);
		if (keycode != null){
			PcControllerAbstract.getMyRobot().keyPress(keycode);
			PcControllerAbstract.getMyRobot().keyRelease(keycode);
			return true;
		}
		return false;
	}
	
}
