/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zooper.becuz.restmote.ui;

import org.zooper.becuz.restmote.ui.model.ListComboBoxModel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ListSelectionEvent;

import org.apache.log4j.Logger;
import org.zooper.becuz.restmote.business.AppBusiness;
import org.zooper.becuz.restmote.business.MediaCategoryBusiness;
import org.zooper.becuz.restmote.business.SettingsBusiness;
import org.zooper.becuz.restmote.controller.PcControllerFactory;
import org.zooper.becuz.restmote.http.InetAddr;
import org.zooper.becuz.restmote.http.Server;
import org.zooper.becuz.restmote.model.App;
import org.zooper.becuz.restmote.model.MediaCategory;
import org.zooper.becuz.restmote.model.Settings;
import org.zooper.becuz.restmote.ui.widgets.IntTextField;
import org.zooper.becuz.restmote.ui.widgets.URLLabel;
import org.zooper.becuz.restmote.utils.Utils;

/**
 *
 * @author admin
 */
public class MainWindow extends javax.swing.JFrame {

    private Logger logger = Logger.getLogger(MainWindow.class.getName());
    
    /**
     * Swing list model for {@link #listPaths} 
     */
    private DefaultListModel<String> listPathsModel;
    
    /**
     * Swing list model for {@link #comboInetNames} 
     */
    private ListComboBoxModel<InetAddr> listInetNamesModel;
	
	/**
     * Swing list model for {@link #comboInetNames} 
     */
    private DefaultComboBoxModel<String> listIconThemesModel;
    
    /**
     * Swing list model for {@link #listCategories} 
     */
    private DefaultListModel<MediaCategory> listMediaCategoryModel;
    
	 /**
     * Swing list model for {@link #listApps} 
     */
    private DefaultListModel<App> listAppsModel;
	
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
		listInetNamesModel = new ListComboBoxModel<InetAddr>();
		listMediaCategoryModel = new DefaultListModel<MediaCategory>();
    	listPathsModel = new DefaultListModel<String>();
		listIconThemesModel = new DefaultComboBoxModel<String>();
		listAppsModel = new DefaultListModel<App>();
		initComponents();
		copyToView();
    }

	private void copyToView(){
		Settings settings = PcControllerFactory.getPcController().getSettingsBusiness().get();
		
		listInetNamesModel.clear();
		listMediaCategoryModel.clear();
		listPathsModel.clear();
		listIconThemesModel.removeAllElements();
		
		listInetNamesModel.addAll(Server.getInstance().getLocalInetAddresses());
		for(MediaCategory mediaCategory: PcControllerFactory.getPcController().getMediaCategoryBusiness().getAll()){
			listMediaCategoryModel.addElement(mediaCategory);
		}
		
		if (!Utils.isEmpty(settings.getServerInetName())){
    		for(InetAddr inetAddr: listInetNamesModel.getAll()){
    			if(inetAddr.getInetName().equals(settings.getServerInetName())){
    				listInetNamesModel.setSelectedItem(inetAddr);
    				break;
    			}
    		}
    	}
    	
    	for(String path: settings.getPaths()){
    		listPathsModel.addElement(path);
    	}
		
		File f = new File(Utils.getRestmoteRootDirAbsolutePath() + System.getProperty("file.separator") + "client" + System.getProperty("file.separator") + "images");
		if (f.exists() && f.isDirectory()){
			File[] children = f.listFiles();
			if (children != null){
				for(File child: children){
					if (child.isDirectory()){
						String dirIcon = child.getPath().substring(child.getPath().lastIndexOf(System.getProperty("file.separator"))+1);
						listIconThemesModel.addElement(dirIcon);
						if (dirIcon.equals(settings.getIconTheme())){
							listIconThemesModel.setSelectedItem(dirIcon);
						}
					}
				}
			}
		}
		
		for(App app: PcControllerFactory.getPcController().getAppBusiness().getAll()){
			listAppsModel.addElement(app);
		}
		
		textFieldPort.setText(""+settings.getServerPort());
        textFieldName.setText(settings.getName());
        textFieldNameRoot.setText(settings.getNameRoot());
        textFieldScanDepth.setText(""+settings.getScanDepth());
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTabs = new javax.swing.JTabbedPane();
        panelSettings = new javax.swing.JPanel();
        panelSettingsPnlServer = new javax.swing.JPanel();
        lblComboInetNames = new javax.swing.JLabel();
        comboInetNames = new javax.swing.JComboBox();
        lblComboPort = new javax.swing.JLabel();
        textFieldPort = new IntTextField(this);
        lblStatusServer = new javax.swing.JLabel();
        btnToggleServer = new javax.swing.JButton();
        lblServerUrl = new URLLabel();
        btnRefreshInetNames = new javax.swing.JButton();
        panelSettingsPnlGeneral = new javax.swing.JPanel();
        lblTextFieldName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        lblTextFieldNameRoot = new javax.swing.JLabel();
        textFieldNameRoot = new javax.swing.JTextField();
        scrollPaneListPaths = new javax.swing.JScrollPane();
        listPaths = new javax.swing.JList();
        btnAddPath = new javax.swing.JButton();
        textFieldPath = new javax.swing.JTextField();
        btnDeletePath = new javax.swing.JButton();
        lblPaths = new javax.swing.JLabel();
        lblTextFieldScanDepth = new javax.swing.JLabel();
        textFieldScanDepth = new javax.swing.JTextField();
        btnBrowsePath = new javax.swing.JButton();
        lblComboIconTheme = new javax.swing.JLabel();
        comboIconTheme = new javax.swing.JComboBox();
        panelCategories = new javax.swing.JPanel();
        panelCategoriesPnlEdit = new javax.swing.JPanel();
        lblTextFieldNameCategory = new javax.swing.JLabel();
        textFieldNameCategory = new javax.swing.JTextField();
        lblTextFieldDescriptionCategory = new javax.swing.JLabel();
        textFieldDescriptionCategory = new javax.swing.JTextField();
        lblTextFieldExtensionsCategory = new javax.swing.JLabel();
        textFieldExtensionsCategory = new javax.swing.JTextField();
        btnEditCategoryCancel = new javax.swing.JButton();
        btnEditCategorySave = new javax.swing.JButton();
        panelCategoriesPnlList = new javax.swing.JPanel();
        lblCategories = new javax.swing.JLabel();
        btnDeleteCategory = new javax.swing.JButton();
        scrollPaneListCategories = new javax.swing.JScrollPane();
        listCategories = new javax.swing.JList();
        btnAddCategory = new javax.swing.JButton();
        panelApps = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileExit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();

        FormListener formListener = new FormListener();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Restmote Control");
        setResizable(false);

        panelSettingsPnlServer.setBorder(javax.swing.BorderFactory.createTitledBorder("Server"));

        lblComboInetNames.setText("Interface");

        comboInetNames.setModel(listInetNamesModel);
        comboInetNames.addActionListener(formListener);

        lblComboPort.setText("Port");

        lblStatusServer.setText("lbl Server Status");

        btnToggleServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/user_green.png"))); // NOI18N
        btnToggleServer.addMouseListener(formListener);
        btnToggleServer.addActionListener(formListener);

        lblServerUrl.setText("lbl Server Url");

        btnRefreshInetNames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/refresh.png"))); // NOI18N
        btnRefreshInetNames.setEnabled(false);

        javax.swing.GroupLayout panelSettingsPnlServerLayout = new javax.swing.GroupLayout(panelSettingsPnlServer);
        panelSettingsPnlServer.setLayout(panelSettingsPnlServerLayout);
        panelSettingsPnlServerLayout.setHorizontalGroup(
            panelSettingsPnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsPnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSettingsPnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblServerUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSettingsPnlServerLayout.createSequentialGroup()
                        .addComponent(comboInetNames, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshInetNames, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSettingsPnlServerLayout.createSequentialGroup()
                        .addGroup(panelSettingsPnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnToggleServer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComboInetNames))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(panelSettingsPnlServerLayout.createSequentialGroup()
                        .addComponent(lblComboPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelSettingsPnlServerLayout.setVerticalGroup(
            panelSettingsPnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsPnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComboInetNames)
                .addGap(5, 5, 5)
                .addGroup(panelSettingsPnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInetNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshInetNames, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSettingsPnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComboPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblServerUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(lblStatusServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToggleServer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelSettingsPnlGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        lblTextFieldName.setLabelFor(lblTextFieldName);
        lblTextFieldName.setText("Name");

        lblTextFieldNameRoot.setLabelFor(textFieldNameRoot);
        lblTextFieldNameRoot.setText("NameRoot");

        listPaths.setModel(listPathsModel);
        listPaths.addListSelectionListener(formListener);
        scrollPaneListPaths.setViewportView(listPaths);

        btnAddPath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/add.png"))); // NOI18N
        btnAddPath.addActionListener(formListener);

        btnDeletePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/delete.png"))); // NOI18N
        btnDeletePath.setEnabled(false);
        btnDeletePath.addActionListener(formListener);

        lblPaths.setText("Here you can choose the directories that the system will monitor for medias");

        lblTextFieldScanDepth.setLabelFor(lblTextFieldScanDepth);
        lblTextFieldScanDepth.setText("ScanDepth");

        btnBrowsePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/folder.png"))); // NOI18N
        btnBrowsePath.addActionListener(formListener);

        lblComboIconTheme.setLabelFor(comboIconTheme);
        lblComboIconTheme.setText("Icon Theme");

        comboIconTheme.setModel(listIconThemesModel);

        javax.swing.GroupLayout panelSettingsPnlGeneralLayout = new javax.swing.GroupLayout(panelSettingsPnlGeneral);
        panelSettingsPnlGeneral.setLayout(panelSettingsPnlGeneralLayout);
        panelSettingsPnlGeneralLayout.setHorizontalGroup(
            panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsPnlGeneralLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaths)
                    .addGroup(panelSettingsPnlGeneralLayout.createSequentialGroup()
                        .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextFieldNameRoot)
                            .addComponent(lblTextFieldName)
                            .addComponent(lblTextFieldScanDepth))
                        .addGap(22, 22, 22)
                        .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNameRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(textFieldScanDepth)
                            .addComponent(textFieldName)))
                    .addGroup(panelSettingsPnlGeneralLayout.createSequentialGroup()
                        .addComponent(lblComboIconTheme)
                        .addGap(18, 18, 18)
                        .addComponent(comboIconTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSettingsPnlGeneralLayout.createSequentialGroup()
                        .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textFieldPath)
                            .addComponent(scrollPaneListPaths, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletePath, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSettingsPnlGeneralLayout.createSequentialGroup()
                                .addComponent(btnBrowsePath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddPath, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSettingsPnlGeneralLayout.setVerticalGroup(
            panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsPnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldName)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldNameRoot)
                    .addComponent(textFieldNameRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldScanDepth)
                    .addComponent(textFieldScanDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComboIconTheme)
                    .addComponent(comboIconTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblPaths)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddPath, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowsePath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSettingsPnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneListPaths, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePath, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSettingsPnlServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSettingsPnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSettingsPnlServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSettingsPnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTabs.addTab("Settings", new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/wrench.png")), panelSettings); // NOI18N

        panelCategoriesPnlEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));

        lblTextFieldNameCategory.setText("Name");

        lblTextFieldDescriptionCategory.setLabelFor(lblTextFieldDescriptionCategory);
        lblTextFieldDescriptionCategory.setText("Description");

        lblTextFieldExtensionsCategory.setText("Extensions");

        btnEditCategoryCancel.setText("Cancel");
        btnEditCategoryCancel.addActionListener(formListener);

        btnEditCategorySave.setText("Save");
        btnEditCategorySave.addActionListener(formListener);

        javax.swing.GroupLayout panelCategoriesPnlEditLayout = new javax.swing.GroupLayout(panelCategoriesPnlEdit);
        panelCategoriesPnlEdit.setLayout(panelCategoriesPnlEditLayout);
        panelCategoriesPnlEditLayout.setHorizontalGroup(
            panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriesPnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCategoriesPnlEditLayout.createSequentialGroup()
                        .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextFieldDescriptionCategory)
                            .addComponent(lblTextFieldNameCategory)
                            .addComponent(lblTextFieldExtensionsCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldDescriptionCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldExtensionsCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCategoriesPnlEditLayout.createSequentialGroup()
                        .addComponent(btnEditCategoryCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditCategorySave)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelCategoriesPnlEditLayout.setVerticalGroup(
            panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriesPnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldNameCategory)
                    .addComponent(textFieldNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldExtensionsCategory)
                    .addComponent(textFieldExtensionsCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDescriptionCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextFieldDescriptionCategory))
                .addGap(18, 18, 18)
                .addGroup(panelCategoriesPnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditCategorySave)
                    .addComponent(btnEditCategoryCancel))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        panelCategoriesPnlList.setBorder(javax.swing.BorderFactory.createTitledBorder("List"));

        lblCategories.setText("Edit one category from below or create a new one:");

        btnDeleteCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/delete.png"))); // NOI18N
        btnDeleteCategory.setEnabled(false);
        btnDeleteCategory.addActionListener(formListener);

        listCategories.setModel(listMediaCategoryModel);
        listCategories.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCategories.addListSelectionListener(formListener);
        scrollPaneListCategories.setViewportView(listCategories);

        btnAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/add.png"))); // NOI18N
        btnAddCategory.addActionListener(formListener);

        javax.swing.GroupLayout panelCategoriesPnlListLayout = new javax.swing.GroupLayout(panelCategoriesPnlList);
        panelCategoriesPnlList.setLayout(panelCategoriesPnlListLayout);
        panelCategoriesPnlListLayout.setHorizontalGroup(
            panelCategoriesPnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriesPnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriesPnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCategoriesPnlListLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneListCategories)
                    .addGroup(panelCategoriesPnlListLayout.createSequentialGroup()
                        .addComponent(lblCategories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(108, 108, 108))
        );
        panelCategoriesPnlListLayout.setVerticalGroup(
            panelCategoriesPnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriesPnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriesPnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneListCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteCategory)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCategoriesLayout = new javax.swing.GroupLayout(panelCategories);
        panelCategories.setLayout(panelCategoriesLayout);
        panelCategoriesLayout.setHorizontalGroup(
            panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCategoriesPnlList, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCategoriesPnlEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCategoriesLayout.setVerticalGroup(
            panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCategoriesPnlEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCategoriesPnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTabs.addTab("Categories", new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/user_green.png")), panelCategories); // NOI18N

        javax.swing.GroupLayout panelAppsLayout = new javax.swing.GroupLayout(panelApps);
        panelApps.setLayout(panelAppsLayout);
        panelAppsLayout.setHorizontalGroup(
            panelAppsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        panelAppsLayout.setVerticalGroup(
            panelAppsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        panelTabs.addTab("Apps", new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/user_orange.png")), panelApps); // NOI18N

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/24/rss.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("");
        btnSave.setIconTextGap(10);
        btnSave.addActionListener(formListener);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        btnCancel.setIconTextGap(10);
        btnCancel.addActionListener(formListener);

        menuFile.setText("File");

        menuFileExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuFileExit.setText("Exit");
        menuFileExit.addMouseListener(formListener);
        menuFileExit.addActionListener(formListener);
        menuFile.add(menuFileExit);

        menuBar.add(menuFile);

        menuAbout.setText("About");
        menuBar.add(menuAbout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTabs)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, javax.swing.event.ListSelectionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == comboInetNames) {
                MainWindow.this.comboInetNamesActionPerformed(evt);
            }
            else if (evt.getSource() == btnToggleServer) {
                MainWindow.this.btnToggleServerActionPerformed(evt);
            }
            else if (evt.getSource() == btnAddPath) {
                MainWindow.this.btnAddPathActionPerformed(evt);
            }
            else if (evt.getSource() == btnDeletePath) {
                MainWindow.this.btnDeletePathActionPerformed(evt);
            }
            else if (evt.getSource() == btnBrowsePath) {
                MainWindow.this.btnBrowsePathActionPerformed(evt);
            }
            else if (evt.getSource() == btnEditCategoryCancel) {
                MainWindow.this.btnEditCategoryCancelActionPerformed(evt);
            }
            else if (evt.getSource() == btnEditCategorySave) {
                MainWindow.this.btnEditCategorySaveActionPerformed(evt);
            }
            else if (evt.getSource() == btnDeleteCategory) {
                MainWindow.this.btnDeleteCategoryActionPerformed(evt);
            }
            else if (evt.getSource() == btnAddCategory) {
                MainWindow.this.btnAddCategoryActionPerformed(evt);
            }
            else if (evt.getSource() == btnSave) {
                MainWindow.this.btnSaveActionPerformed(evt);
            }
            else if (evt.getSource() == btnCancel) {
                MainWindow.this.btnCancelActionPerformed(evt);
            }
            else if (evt.getSource() == menuFileExit) {
                MainWindow.this.menuFileExitActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == btnToggleServer) {
                MainWindow.this.btnToggleServerMousePressed(evt);
            }
            else if (evt.getSource() == menuFileExit) {
                MainWindow.this.menuFileExitMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            if (evt.getSource() == listPaths) {
                MainWindow.this.listPathsValueChanged(evt);
            }
            else if (evt.getSource() == listCategories) {
                MainWindow.this.listCategoriesValueChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileExitActionPerformed
        logger.info("menuFileExitActionPerformed");
        System.exit(0);
    }//GEN-LAST:event_menuFileExitActionPerformed

    private void btnToggleServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleServerActionPerformed
        try {
            if (Server.getInstance().isRunning()){
                Server.getInstance().stop();
                lblStatusServer.setText("Http Server is not running");
                btnToggleServer.setText("Start");
            } else {
                Server.getInstance().start(listInetNamesModel.getSelectedItem().getInetName(), ((IntTextField)textFieldPort).getValue());
                lblStatusServer.setText("Http Server is running!");
                btnToggleServer.setText("Stop");
            }
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_btnToggleServerActionPerformed
    
    private void btnToggleServerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToggleServerMousePressed
        
    }//GEN-LAST:event_btnToggleServerMousePressed

    private void menuFileExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_menuFileExitMousePressed

    public void refreshLblServerUrl(){
        InetAddr inetAddr = listInetNamesModel.getSelectedItem();
        String url = inetAddr == null ? "" : "http://" + inetAddr.getIp() + ":" + ((IntTextField)textFieldPort).getValue() + "/client/index.html";
        lblServerUrl.setText(url);
        ((URLLabel)lblServerUrl).setURL(url);
    }
    
    private void comboInetNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInetNamesActionPerformed
        refreshLblServerUrl();
    }//GEN-LAST:event_comboInetNamesActionPerformed

    private void listPathsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPathsValueChanged
        if (evt.getValueIsAdjusting() == false) {
            btnDeletePath.setEnabled(listPaths.getSelectedIndex() != -1);
        }
    }//GEN-LAST:event_listPathsValueChanged

    private void btnDeletePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePathActionPerformed
        int[] indexes = listPaths.getSelectedIndices();
        for (int i = 0; i < indexes.length; i++) {
            listPathsModel.remove(indexes[i] - i);
        }
        btnDeletePath.setEnabled(false);
    }//GEN-LAST:event_btnDeletePathActionPerformed

    private void btnAddPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPathActionPerformed
       String name = textFieldPath.getText();
       if (name.equals("") || listPathsModel.contains(name)) {
            Toolkit.getDefaultToolkit().beep();
            textFieldPath.requestFocusInWindow();
            textFieldPath.selectAll();
            return;
       }
       int index = listPaths.getSelectedIndex() + 1;
       listPathsModel.insertElementAt(name, index);
       textFieldPath.requestFocusInWindow();
       textFieldPath.setText("");
       //listPaths.setSelectedIndex(index);
       //listPaths.ensureIndexIsVisible(index);
    }//GEN-LAST:event_btnAddPathActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        SettingsBusiness settingsBusiness = PcControllerFactory.getPcController().getSettingsBusiness();
        Settings settings = settingsBusiness.get();
        settings.setServerPort(Integer.parseInt(textFieldPort.getText()));
        InetAddr inetAddr = listInetNamesModel.getSelectedItem();
        settings.setServerInetName(inetAddr.getInetName());
        settings.setServerLastIp(inetAddr.getIp());
        Set<String> paths = new HashSet<String>(); 
        for (int i = 0; i < listPathsModel.size(); i++) {
            paths.add(listPathsModel.get(i));
        }
        settings.setPaths(paths);
        settings.setName(textFieldName.getText());
        settings.setNameRoot(textFieldNameRoot.getText());
        settings.setScanDepth(Integer.parseInt(textFieldScanDepth.getText()));
        settings.setIconTheme(listIconThemesModel.getSelectedItem().toString());
        settingsBusiness.store(settings);
		
        MediaCategoryBusiness mediaCategoryBusiness = PcControllerFactory.getPcController().getMediaCategoryBusiness();
        for (int i = 0; i < listMediaCategoryModel.size(); i++) {
        	mediaCategoryBusiness.store(listMediaCategoryModel.get(i));
		}
        setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteCategoryActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
    private void panelTabsStateChanged(ChangeEvent evt) {
       logger.info("Not yet implemented");
    }

    private void listActiveAppsValueChanged(ListSelectionEvent evt) {
        logger.info("Not yet implemented");
    }

    
    
    private void editMediaCategory(MediaCategory mediaCategory){
        textFieldNameCategory.setText(mediaCategory == null ? "" : mediaCategory.getName());
        textFieldDescriptionCategory.setText(mediaCategory == null ? "" : mediaCategory.getDescription());
        textFieldExtensionsCategory.setText(mediaCategory == null ? "" : Utils.join(mediaCategory.getExtensions(), ","));
    }
    
    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        MediaCategory mediaCategory = new MediaCategory("name");
        listMediaCategoryModel.insertElementAt(mediaCategory, 0);
        listCategories.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void btnBrowsePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePathActionPerformed
        // TODO dire chooser dialog box
    }//GEN-LAST:event_btnBrowsePathActionPerformed

    private void btnEditCategoryCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCategoryCancelActionPerformed
        listCategories.clearSelection();
    }//GEN-LAST:event_btnEditCategoryCancelActionPerformed

    private void btnEditCategorySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCategorySaveActionPerformed
    	int selectedIndex = listCategories.getSelectedIndex();
    	MediaCategory mediaCategory = selectedIndex == -1 ? null : listMediaCategoryModel.getElementAt(selectedIndex);
        if (mediaCategory != null){
            mediaCategory.setName(textFieldNameCategory.getText());
            mediaCategory.setDescription(textFieldDescriptionCategory.getText());
            mediaCategory.setExtensions(new HashSet<>(Arrays.asList(textFieldExtensionsCategory.getText().split(","))));
        }
    }//GEN-LAST:event_btnEditCategorySaveActionPerformed

    private void listCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCategoriesValueChanged
    	int selectedIndex = listCategories.getSelectedIndex();
    	if (evt.getValueIsAdjusting() == false) {
            btnDeleteCategory.setEnabled(selectedIndex > -1);
        }
        MediaCategory mediaCategory = selectedIndex == -1 ? null : listMediaCategoryModel.getElementAt(selectedIndex);
        editMediaCategory(mediaCategory);
    }//GEN-LAST:event_listCategoriesValueChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
		textFieldPath.setText("");
		copyToView();
    }//GEN-LAST:event_btnCancelActionPerformed

    
    
    public javax.swing.JTextField getTextFieldDescriptionCategory() {
		return textFieldDescriptionCategory;
	}

	public javax.swing.JTextField getTextFieldExtensionsCategory() {
		return textFieldExtensionsCategory;
	}

	public javax.swing.JTextField getTextFieldNameCategory() {
		return textFieldNameCategory;
	}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddPath;
    private javax.swing.JButton btnBrowsePath;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteCategory;
    private javax.swing.JButton btnDeletePath;
    private javax.swing.JButton btnEditCategoryCancel;
    private javax.swing.JButton btnEditCategorySave;
    private javax.swing.JButton btnRefreshInetNames;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnToggleServer;
    private javax.swing.JComboBox comboIconTheme;
    private javax.swing.JComboBox comboInetNames;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblComboIconTheme;
    private javax.swing.JLabel lblComboInetNames;
    private javax.swing.JLabel lblComboPort;
    private javax.swing.JLabel lblPaths;
    private javax.swing.JLabel lblServerUrl;
    private javax.swing.JLabel lblStatusServer;
    private javax.swing.JLabel lblTextFieldDescriptionCategory;
    private javax.swing.JLabel lblTextFieldExtensionsCategory;
    private javax.swing.JLabel lblTextFieldName;
    private javax.swing.JLabel lblTextFieldNameCategory;
    private javax.swing.JLabel lblTextFieldNameRoot;
    private javax.swing.JLabel lblTextFieldScanDepth;
    private javax.swing.JList listCategories;
    private javax.swing.JList listPaths;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileExit;
    private javax.swing.JPanel panelApps;
    private javax.swing.JPanel panelCategories;
    private javax.swing.JPanel panelCategoriesPnlEdit;
    private javax.swing.JPanel panelCategoriesPnlList;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JPanel panelSettingsPnlGeneral;
    private javax.swing.JPanel panelSettingsPnlServer;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JScrollPane scrollPaneListCategories;
    private javax.swing.JScrollPane scrollPaneListPaths;
    private javax.swing.JTextField textFieldDescriptionCategory;
    private javax.swing.JTextField textFieldExtensionsCategory;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldNameCategory;
    private javax.swing.JTextField textFieldNameRoot;
    private javax.swing.JTextField textFieldPath;
    private javax.swing.JTextField textFieldPort;
    private javax.swing.JTextField textFieldScanDepth;
    // End of variables declaration//GEN-END:variables

  

    
}
