package org.zooper.becuz.restmote.ui.panels;

import java.util.Arrays;
import java.util.Enumeration;
import java.util.HashSet;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;

import org.zooper.becuz.restmote.model.App;
import org.zooper.becuz.restmote.model.MediaCategory;
import org.zooper.becuz.restmote.model.interfaces.Persistable;
import org.zooper.becuz.restmote.ui.UIConstants;
import org.zooper.becuz.restmote.utils.Constants;
import org.zooper.becuz.restmote.utils.Utils;

/**
 *
 * @author bebo
 */
@SuppressWarnings("serial")
public class PanelEditCategory extends PanelPersistable {

	private DefaultComboBoxModel<App> comboAppsModel = new DefaultComboBoxModel<App>();
	

	/**
	 * Creates new form PanelEditCategory
	 */
	public PanelEditCategory() {
		initComponents();
		jComponentsToObserve = new JComponent[]{
			textFieldNameCategory, textFieldDescriptionCategory, textFieldExtensionsCategory, 
			comboCategoryApp, checkCategoryActive};
		activateViewChangesListener();
	}
	
	public PanelEditCategory(PanelListPersistable panelListPersistable) {
		this();
		this.panelListPersistable = panelListPersistable;
	}
	
	/**
	 * Set the the model of comboAppsModel, with the updated apps list
	 * @param apps 
	 */
	public void setModelAppData(Enumeration<Persistable> apps){
		App prevSelectedApp = (App) comboAppsModel.getSelectedItem(); 
		comboAppsModel.removeAllElements();
		while (apps.hasMoreElements()) {
			App app = (App) apps.nextElement();
			comboAppsModel.addElement(app);
		}
		if (prevSelectedApp != null){
			comboAppsModel.setSelectedItem(prevSelectedApp);
		}
	}
	
	@Override
	public void edit(Persistable p){
		super.edit(p);
		MediaCategory mediaCategory = (MediaCategory) p;
        textFieldNameCategory.setText(mediaCategory == null ? "" : mediaCategory.getName());
        textFieldDescriptionCategory.setText(mediaCategory == null ? "" : mediaCategory.getDescription());
        textFieldExtensionsCategory.setText(mediaCategory == null ? "" : Utils.join(mediaCategory.getExtensions(), ","));
		comboCategoryApp.setSelectedItem(mediaCategory == null ? null : mediaCategory.getApp());
		checkCategoryActive.setSelected(mediaCategory == null ? false : mediaCategory.getActive());
		textFieldNameCategory.setEnabled(mediaCategory != null && !mediaCategory.getName().equals(Constants.MEDIA_ROOT));
		textFieldDescriptionCategory.setEnabled(mediaCategory != null && !mediaCategory.getName().equals(Constants.MEDIA_ROOT));
		textFieldExtensionsCategory.setEnabled(mediaCategory != null && !mediaCategory.getName().equals(Constants.MEDIA_ROOT));
		comboCategoryApp.setEnabled(mediaCategory != null && !mediaCategory.getName().equals(Constants.MEDIA_ROOT));
		listenViewChanges = true;
    }

	
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextFieldNameCategory = new javax.swing.JLabel();
        textFieldNameCategory = new javax.swing.JTextField();
        lblTextFieldDescriptionCategory = new javax.swing.JLabel();
        textFieldDescriptionCategory = new javax.swing.JTextField();
        lblTextFieldExtensionsCategory = new javax.swing.JLabel();
        textFieldExtensionsCategory = new javax.swing.JTextField();
        btnEditCategoryCancel = new javax.swing.JButton();
        btnEditCategorySave = new javax.swing.JButton();
        comboCategoryApp = new javax.swing.JComboBox<App>();
        lblCategoryApp = new javax.swing.JLabel();
        checkCategoryActive = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));

        lblTextFieldNameCategory.setFont(lblTextFieldNameCategory.getFont().deriveFont(lblTextFieldNameCategory.getFont().getStyle() | java.awt.Font.BOLD));
        lblTextFieldNameCategory.setText("Name:");
        lblTextFieldNameCategory.setToolTipText(UIConstants.TOOLTIP_CATEGORY_NAME);

        lblTextFieldDescriptionCategory.setText("Description:");
        lblTextFieldDescriptionCategory.setToolTipText(UIConstants.TOOLTIP_CATEGORY_DESCRIPTION);

        lblTextFieldExtensionsCategory.setFont(lblTextFieldExtensionsCategory.getFont().deriveFont(lblTextFieldExtensionsCategory.getFont().getStyle() | java.awt.Font.BOLD));
        lblTextFieldExtensionsCategory.setText("Extensions:");
        lblTextFieldExtensionsCategory.setToolTipText(UIConstants.TOOLTIP_CATEGORY_EXTENSIONS);

        btnEditCategoryCancel.setText("Cancel");
        btnEditCategoryCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCategoryCancelActionPerformed(evt);
            }
        });

        btnEditCategorySave.setText("Save");
        btnEditCategorySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCategorySaveActionPerformed(evt);
            }
        });

        comboCategoryApp.setModel(comboAppsModel);

        lblCategoryApp.setText("App:");
        lblCategoryApp.setToolTipText(UIConstants.TOOLTIP_CATEGORY_APP);

        checkCategoryActive.setText("Active");
        checkCategoryActive.setToolTipText(UIConstants.TOOLTIP_CATEGORY_ACTIVE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextFieldNameCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTextFieldExtensionsCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTextFieldDescriptionCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCategoryApp, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNameCategory)
                    .addComponent(textFieldExtensionsCategory)
                    .addComponent(textFieldDescriptionCategory)
                    .addComponent(comboCategoryApp, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(btnEditCategorySave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCategoryCancel)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(checkCategoryActive)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditCategoryCancel, btnEditCategorySave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkCategoryActive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldNameCategory)
                    .addComponent(textFieldNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFieldExtensionsCategory)
                    .addComponent(textFieldExtensionsCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDescriptionCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextFieldDescriptionCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategoryApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoryApp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditCategorySave)
                    .addComponent(btnEditCategoryCancel))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditCategoryCancel, btnEditCategorySave});

    }// </editor-fold>//GEN-END:initComponents

    private void btnEditCategoryCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCategoryCancelActionPerformed
        panelListPersistable.clearSelection();
    }//GEN-LAST:event_btnEditCategoryCancelActionPerformed

    private void btnEditCategorySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCategorySaveActionPerformed
        Persistable p = panelListPersistable.getSelectedItem();
		if (p != null){
            MediaCategory mediaCategory = (MediaCategory) p;
            mediaCategory.setName(textFieldNameCategory.getText());
            mediaCategory.setDescription(textFieldDescriptionCategory.getText());
            mediaCategory.setExtensions(new HashSet<>(Arrays.asList(textFieldExtensionsCategory.getText().split(","))));
			mediaCategory.setApp(comboAppsModel.getSelectedItem() == null ? null : (App) comboAppsModel.getSelectedItem());
			mediaCategory.setActive(checkCategoryActive.isSelected());
        }
        panelListPersistable.clearSelection();
    }//GEN-LAST:event_btnEditCategorySaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCategoryCancel;
    private javax.swing.JButton btnEditCategorySave;
    private javax.swing.JCheckBox checkCategoryActive;
    private javax.swing.JComboBox comboCategoryApp;
    private javax.swing.JLabel lblCategoryApp;
    private javax.swing.JLabel lblTextFieldDescriptionCategory;
    private javax.swing.JLabel lblTextFieldExtensionsCategory;
    private javax.swing.JLabel lblTextFieldNameCategory;
    private javax.swing.JTextField textFieldDescriptionCategory;
    private javax.swing.JTextField textFieldExtensionsCategory;
    private javax.swing.JTextField textFieldNameCategory;
    // End of variables declaration//GEN-END:variables

	

	
}
