/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zooper.becuz.restmote.ui.panels;

import java.util.List;

import javax.swing.DefaultListModel;

import org.zooper.becuz.restmote.business.MediaCategoryBusiness;
import org.zooper.becuz.restmote.controller.PcControllerFactory;
import org.zooper.becuz.restmote.model.MediaCategory;
import org.zooper.becuz.restmote.model.interfaces.Persistable;

/**
 *
 * @author admin
 */
public class PanelCategories extends javax.swing.JPanel implements PanelPersistables{

	/**
     * Swing list model
     */
    private DefaultListModel<Persistable> listModel = new DefaultListModel<Persistable>();
	
	/**
	 * Creates new form PanelCategories
	 */
	public PanelCategories() {
		initComponents();
		panelEditCategories.setEnabled(false);
	}

	@Override
	public void copyToView() {
		listModel.clear();
		List<MediaCategory> mediaCategories = PcControllerFactory.getPcController().getMediaCategoryBusiness().getAll();
		if (mediaCategories != null){
			for(MediaCategory mediaCategory: mediaCategories){
				listModel.addElement(mediaCategory);
			}
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListPersistable = new org.zooper.becuz.restmote.ui.panels.PanelListPersistable(this);
        panelEditCategories = new org.zooper.becuz.restmote.ui.panels.PanelEditCategories(panelListPersistable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelListPersistable, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEditCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEditCategories, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListPersistable, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.zooper.becuz.restmote.ui.panels.PanelEditCategories panelEditCategories;
    private org.zooper.becuz.restmote.ui.panels.PanelListPersistable panelListPersistable;
    // End of variables declaration//GEN-END:variables

	@Override
	public Persistable getNew() {
		return new MediaCategory("name");
	}

	@Override
	public void edit(Persistable p) {
		panelEditCategories.editMediaCategory((MediaCategory)p);
	}

	@Override
	public DefaultListModel<Persistable> getListModel() {
		return listModel;
	}
	
	public PanelEditCategories getPanelEditCategories(){
		return panelEditCategories;
	}
	
	@Override
	public void save() {
		MediaCategoryBusiness mediaCategoryBusiness = PcControllerFactory.getPcController().getMediaCategoryBusiness();
        for (int i = 0; i < listModel.size(); i++) {
        	mediaCategoryBusiness.store(listModel.get(i));
		}
		for(Persistable p: panelListPersistable.getBin()){
			mediaCategoryBusiness.delete((MediaCategory)p);
		}
	}
	
}
