/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zooper.becuz.restmote.ui.panels;

import java.util.Arrays;
import java.util.HashSet;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

import org.zooper.becuz.restmote.model.App;
import org.zooper.becuz.restmote.model.Control;
import org.zooper.becuz.restmote.ui.UIUtils;
import org.zooper.becuz.restmote.ui.appcontrols.AppTableModel;
import org.zooper.becuz.restmote.ui.appcontrols.ControlRenderer;
import org.zooper.becuz.restmote.ui.appcontrols.ControlSelectionListener;
import org.zooper.becuz.restmote.ui.appcontrols.ControlsTable;
import org.zooper.becuz.restmote.ui.appcontrols.ImageList;
import org.zooper.becuz.restmote.ui.appcontrols.ImageListTransferHandler;
import org.zooper.becuz.restmote.utils.Utils;

/**
 *
 * @author bebo
 */
@SuppressWarnings("serial")
public class PanelEditApps extends javax.swing.JPanel {

	
	
	private JList listApps;
	private DefaultListModel<App> listAppsModel;
	
	 /**
     * 
     */
    private AppTableModel appTableModel = new AppTableModel();
	
	
	public PanelEditApps(JList listApps, DefaultListModel<App> listAppsModel) {
		this();
		this.listApps = listApps;
		this.listAppsModel = listAppsModel;
	}
	
	
	/**
	 * Creates new form PanelEditApps
	 */
	public PanelEditApps() {
		initComponents();
		lblImgSelectedControl.setHorizontalAlignment(JLabel.CENTER);
		lblImgSelectedControl.setTransferHandler(new ImageListTransferHandler());
		tableControls.setDefaultRenderer(Control.class, new ControlRenderer(ImageList.getImageListModel()));
		tableControls.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		ControlSelectionListener controlSelectionlistener = new ControlSelectionListener(this);
//		controlSelectionlistener.addControlSelectionChangedListener(new ControlSelectionChanged() {
//			@Override
//			public void selectionChanged(Control control) {
//				
//			}
//		});
		tableControls.getSelectionModel().addListSelectionListener(controlSelectionlistener);
		tableControls.getColumnModel().getSelectionModel().addListSelectionListener(controlSelectionlistener);
	}
	
	public void editControl(Control control){
		textFieldSelectedControl.setText(control == null ? "" : control.getName());
		lblImgSelectedControl.setIcon(control == null ? null : ImageList.getImageListModel().getImageIcon(control.getName()));
		//lblImgSelectedControl.repaint();
		panelControlKeys.setControl(control);
	}
	
	public void editApp(App app){
        textFieldNameApp.setText(app == null ? "" : app.getName());
        //textFieldDescriptionApp.setText(app == null ? "" : app.getDescription());
        textFieldExtensionsApp.setText(app == null ? "" : Utils.join(app.getExtensions(), ","));
		checkInstanceApp.setSelected(app == null ? false : app.isForceOneInstance());
		textFieldArgFileApp.setText(app == null ? "" : app.getArgumentsFile());
		textFieldArgDirApp.setText(app == null ? "" : app.getArgumentsDir());
		textFieldPathApp.setText(app == null ? "" : app.getPath());
		if (app != null){
			appTableModel.setData(app.getControlsManager());
		} else {
			appTableModel.clearData();
		}
    }
	

	public javax.swing.JTable getTableControls() {
		return tableControls;
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditAppCancel = new javax.swing.JButton();
        btnEditAppSave = new javax.swing.JButton();
        btnEdirAppTest = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        panelConfiguration = new javax.swing.JPanel();
        lblTextFieldNameApp = new javax.swing.JLabel();
        textFieldNameApp = new javax.swing.JTextField();
        lblTextFieldDescriptionApp = new javax.swing.JLabel();
        textFieldDescriptionApp = new javax.swing.JTextField();
        lblTextFieldExtensionsApp = new javax.swing.JLabel();
        textFieldExtensionsApp = new javax.swing.JTextField();
        checkInstanceApp = new javax.swing.JCheckBox();
        lblTextFieldArgFileApp = new javax.swing.JLabel();
        textFieldArgFileApp = new javax.swing.JTextField();
        textFieldArgDirApp = new javax.swing.JTextField();
        lblTextFieldArgDirApp = new javax.swing.JLabel();
        lblTextFieldPathApp = new javax.swing.JLabel();
        textFieldPathApp = new javax.swing.JTextField();
        btnBrowsePath1 = new javax.swing.JButton();
        panelControls = new javax.swing.JPanel();
        panelControlKeys = new org.zooper.becuz.restmote.ui.appcontrols.PanelControlKeys();
        scrollPaneTableControls = new javax.swing.JScrollPane();
        tableControls = new ControlsTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        listImages = new ImageList(false);
        textFieldSelectedControl = new javax.swing.JTextField();
        lblImgSelectedControl = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnDeleteControl = new javax.swing.JButton();

        btnEditAppCancel.setText("Cancel");
        btnEditAppCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAppCancelActionPerformed(evt);
            }
        });

        btnEditAppSave.setText("Save");
        btnEditAppSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAppSaveActionPerformed(evt);
            }
        });

        btnEdirAppTest.setText("Test");

        lblTextFieldNameApp.setText("Name");

        lblTextFieldDescriptionApp.setText("Description");
        lblTextFieldDescriptionApp.setEnabled(false);

        textFieldDescriptionApp.setEnabled(false);

        lblTextFieldExtensionsApp.setText("Extensions");

        textFieldExtensionsApp.setToolTipText("Comma separated list of extensions. Example: .mp3, .m3u, .ogg");

        checkInstanceApp.setText("One Instance");

        lblTextFieldArgFileApp.setText("Arg file");

        lblTextFieldArgDirApp.setText("Arg dir");

        lblTextFieldPathApp.setText("Path");

        btnBrowsePath1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/folder.png"))); // NOI18N
        btnBrowsePath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePath1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfigurationLayout = new javax.swing.GroupLayout(panelConfiguration);
        panelConfiguration.setLayout(panelConfigurationLayout);
        panelConfigurationLayout.setHorizontalGroup(
            panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelConfigurationLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelConfigurationLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(lblTextFieldPathApp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelConfigurationLayout.createSequentialGroup()
                                    .addComponent(textFieldNameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelConfigurationLayout.createSequentialGroup()
                                    .addComponent(textFieldPathApp, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBrowsePath1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                        .addGroup(panelConfigurationLayout.createSequentialGroup()
                            .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelConfigurationLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(lblTextFieldNameApp)
                                    .addGap(171, 171, 171)
                                    .addComponent(lblTextFieldExtensionsApp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textFieldExtensionsApp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelConfigurationLayout.createSequentialGroup()
                                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTextFieldDescriptionApp)
                                        .addComponent(lblTextFieldArgFileApp))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldDescriptionApp, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelConfigurationLayout.createSequentialGroup()
                                            .addComponent(textFieldArgFileApp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(lblTextFieldArgDirApp)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textFieldArgDirApp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(checkInstanceApp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(61, 61, 61)))
                    .addGap(14, 14, 14)))
        );
        panelConfigurationLayout.setVerticalGroup(
            panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelConfigurationLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTextFieldNameApp)
                        .addComponent(textFieldNameApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTextFieldExtensionsApp)
                        .addComponent(textFieldExtensionsApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextFieldPathApp)
                            .addComponent(textFieldPathApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnBrowsePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldDescriptionApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTextFieldDescriptionApp))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextFieldArgFileApp)
                            .addComponent(textFieldArgFileApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextFieldArgDirApp))
                        .addComponent(textFieldArgDirApp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkInstanceApp))
                    .addContainerGap(151, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("Configuration", panelConfiguration);

        tableControls.setModel(appTableModel);
        tableControls.setCellSelectionEnabled(true);
        tableControls.setRowHeight(32);
        tableControls.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tableControls.setTableHeader(null);
        scrollPaneTableControls.setViewportView(tableControls);

        listImages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listImages.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane1.setViewportView(listImages);

        lblImgSelectedControl.setToolTipText("");
        lblImgSelectedControl.setBorder(new javax.swing.border.MatteBorder(null));

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton1");

        javax.swing.GroupLayout panelControlsLayout = new javax.swing.GroupLayout(panelControls);
        panelControls.setLayout(panelControlsLayout);
        panelControlsLayout.setHorizontalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(scrollPaneTableControls, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImgSelectedControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldSelectedControl, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelControlKeys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelControlsLayout.setVerticalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSelectedControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImgSelectedControl, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(jRadioButton2)))
                    .addComponent(panelControlKeys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTableControls, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Controls", panelControls);

        btnDeleteControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/delete.png"))); // NOI18N
        btnDeleteControl.setEnabled(false);
        btnDeleteControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEdirAppTest)
                .addGap(30, 30, 30)
                .addComponent(btnDeleteControl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(btnEditAppSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditAppCancel)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditAppCancel)
                        .addComponent(btnEditAppSave)
                        .addComponent(btnEdirAppTest))
                    .addComponent(btnDeleteControl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAppCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAppCancelActionPerformed
        //TODO il panel edit non scrive sul modello, ma il panel dei controls si
		listApps.clearSelection();
    }//GEN-LAST:event_btnEditAppCancelActionPerformed

	@Override
	public void setEnabled(boolean enabled) {
		super.setEnabled(enabled);
		UIUtils.setEnabledRecursive(this, enabled);
	}
	
	
	
    private void btnEditAppSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAppSaveActionPerformed
		int selectedIndex = listApps.getSelectedIndex();
        App app = selectedIndex == -1 ? null : listAppsModel.getElementAt(selectedIndex);
        if (app != null){
            app.setName(textFieldNameApp.getText());
            //app.setDescription(textFieldDescriptionCategory.getText());
            app.setExtensions(new HashSet<>(Arrays.asList(textFieldExtensionsApp.getText().split(","))));
            app.setForceOneInstance(checkInstanceApp.isSelected());
            app.setArgumentsFile(textFieldArgFileApp.getText());
            app.setArgumentsDir(textFieldArgDirApp.getText());
            app.setPath(textFieldPathApp.getText());
			//TODO il panel edit non scrive sul modello, ma il panel dei controls si
			app.getControlsManager().getControls().clear();
			for (int i = 0; i < tableControls.getRowCount(); i++) {
				for (int j = 0; j < tableControls.getColumnCount(); j++) {
					Control c = (Control) tableControls.getModel().getValueAt(i, j);
					if (c != null){
						app.getControlsManager().addControl(c);
					}
				}
			}
        }
        listApps.clearSelection();
    }//GEN-LAST:event_btnEditAppSaveActionPerformed

    private void btnBrowsePath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowsePath1ActionPerformed

    private void btnDeleteControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteControlActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowsePath1;
    private javax.swing.JButton btnDeleteControl;
    private javax.swing.JButton btnEdirAppTest;
    private javax.swing.JButton btnEditAppCancel;
    private javax.swing.JButton btnEditAppSave;
    private javax.swing.JCheckBox checkInstanceApp;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblImgSelectedControl;
    private javax.swing.JLabel lblTextFieldArgDirApp;
    private javax.swing.JLabel lblTextFieldArgFileApp;
    private javax.swing.JLabel lblTextFieldDescriptionApp;
    private javax.swing.JLabel lblTextFieldExtensionsApp;
    private javax.swing.JLabel lblTextFieldNameApp;
    private javax.swing.JLabel lblTextFieldPathApp;
    private javax.swing.JList listImages;
    private javax.swing.JPanel panelConfiguration;
    private org.zooper.becuz.restmote.ui.appcontrols.PanelControlKeys panelControlKeys;
    private javax.swing.JPanel panelControls;
    private javax.swing.JScrollPane scrollPaneTableControls;
    private javax.swing.JTable tableControls;
    private javax.swing.JTextField textFieldArgDirApp;
    private javax.swing.JTextField textFieldArgFileApp;
    private javax.swing.JTextField textFieldDescriptionApp;
    private javax.swing.JTextField textFieldExtensionsApp;
    private javax.swing.JTextField textFieldNameApp;
    private javax.swing.JTextField textFieldPathApp;
    private javax.swing.JTextField textFieldSelectedControl;
    // End of variables declaration//GEN-END:variables
}
