/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zooper.becuz.restmote.ui.panels;

import javax.swing.JComponent;
import org.zooper.becuz.restmote.model.Command;
import org.zooper.becuz.restmote.model.interfaces.Persistable;
import org.zooper.becuz.restmote.ui.UIConstants;

/**
 *
 * @author admin
 */
public class PanelEditCommand extends PanelPersistable {

	/**
	 * Creates new form PanelEditCommand
	 */
	public PanelEditCommand() {
		initComponents();
		jComponentsToObserve = new JComponent[]{
			textFieldName, textFieldCommand};
		activateViewChangesListener();
	}

	public PanelEditCommand(PanelListPersistable panelListPersistable) {
		this();
		this.panelListPersistable = panelListPersistable;
	}
	
	@Override
	public void edit(Persistable p){
		super.edit(p);
		Command command = (Command) p;
        textFieldName.setText(command == null ? "" : command.getName());
        textFieldCommand.setText(command == null ? "" : command.getCommand());
		listenViewChanges = true;
    }
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextFieldName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        lblTextFieldCommand = new javax.swing.JLabel();
        textFieldCommand = new javax.swing.JTextField();
        btnEditSave = new javax.swing.JButton();
        btnEditCancel = new javax.swing.JButton();

        lblTextFieldName.setFont(lblTextFieldName.getFont().deriveFont(lblTextFieldName.getFont().getStyle() | java.awt.Font.BOLD));
        lblTextFieldName.setText("Name:");
        lblTextFieldName.setToolTipText(UIConstants.TOOLTIP_COMMAND_NAME);

        lblTextFieldCommand.setFont(lblTextFieldCommand.getFont().deriveFont(lblTextFieldCommand.getFont().getStyle() | java.awt.Font.BOLD));
        lblTextFieldCommand.setText("Command:");
        lblTextFieldCommand.setToolTipText(UIConstants.TOOLTIP_COMMAND_COMMAND);

        btnEditSave.setText("Save");
        btnEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaveActionPerformed(evt);
            }
        });

        btnEditCancel.setText("Cancel");
        btnEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTextFieldCommand, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addComponent(textFieldCommand)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditCancel)))
                    .addGap(9, 9, 9)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTextFieldName)
                        .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTextFieldCommand)
                        .addComponent(textFieldCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(72, 72, 72)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditSave)
                        .addComponent(btnEditCancel))
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaveActionPerformed
        Persistable p = panelListPersistable.getSelectedItem();
        if (p != null){
            Command command = (Command) p;
            command.setName(textFieldName.getText());
            command.setCommand(textFieldCommand.getText());
        }
        panelListPersistable.clearSelection();
    }//GEN-LAST:event_btnEditSaveActionPerformed

    private void btnEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCancelActionPerformed
        panelListPersistable.clearSelection();
    }//GEN-LAST:event_btnEditCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCancel;
    private javax.swing.JButton btnEditSave;
    private javax.swing.JLabel lblTextFieldCommand;
    private javax.swing.JLabel lblTextFieldName;
    private javax.swing.JTextField textFieldCommand;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables
}
