/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zooper.becuz.restmote.ui.oop;

import org.zooper.becuz.restmote.business.AppBusiness;
import org.zooper.becuz.restmote.model.App;
import org.zooper.becuz.restmote.model.MediaCategory;
import org.zooper.becuz.restmote.model.interfaces.Persistable;
import org.zooper.becuz.restmote.ui.MainWindow;
import org.zooper.becuz.restmote.utils.Utils;

/**
 *
 * @author admin
 */
public class JPanelListApps extends JPList {

	public JPanelListApps(){
		super();
	}
	
	public JPanelListApps(MainWindow mainWindow, AppBusiness appBusiness) {
		super(mainWindow, appBusiness);
	}

	@Override
	protected void edit(Persistable p) {
		App app = (App) p;
		//mainWindow.getTextFieldNameCategory().setText(mediaCategory == null ? "" : mediaCategory.getName());
		//mainWindow.getTextFieldDescriptionCategory().setText(mediaCategory == null ? "" : mediaCategory.getDescription());
		//mainWindow.getTextFieldExtensionsCategory().setText(mediaCategory == null ? "" : Utils.join(mediaCategory.getExtensions(), ","));
	}

	@Override
	protected Persistable create() {
		return new App("name");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
