/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zooper.becuz.restmote.ui.oop;

import javax.swing.DefaultListModel;
import javax.swing.JPanel;

import org.zooper.becuz.restmote.business.interfaces.BusinessModelAbstract;
import org.zooper.becuz.restmote.model.interfaces.Persistable;
import org.zooper.becuz.restmote.ui.MainWindow;

/**
 *
 * @author admin
 */
public abstract class JPList extends javax.swing.JPanel {

	private String namepippo;
	private JPanel jPanelExtra;
	
	/**
	 * 
	 */
	protected MainWindow mainWindow;
	
	 /**
    * Swing list model for {@link #listCategories} 
    */
	protected DefaultListModel<Persistable> listModel = new DefaultListModel<Persistable>();
	
	/**
	 * 
	 */
	protected BusinessModelAbstract<?> businessModel;
	
	/**
	 * Creates new form JPList
	 */
	public JPList() {
		initComponents();
	}
	
	public JPList(MainWindow mainWindow, BusinessModelAbstract<?> businessModel) {
		this.mainWindow = mainWindow;
		this.businessModel = businessModel;
		initComponents();
		copyToView();
    }

	private void copyToView(){
		for(Persistable p: businessModel.getAll()){
			listModel.addElement(p);
		}
	}
	
	

	public JPanel getjPanelExtra() {
		return jPanelExtra;
	}

	public void setjPanelExtra(JPanel jPanelExtra) {
		this.jPanelExtra = jPanelExtra;
	}

	public String getNamepippo() {
		return namepippo;
	}

	public void setNamepippo(String namepippo) {
		this.namepippo = namepippo;
	}

	protected abstract void edit(Persistable p);
	protected abstract Persistable create();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        scrollPaneList = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        btnDelete = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("List"));

        lbl.setText("Edit one category from below or create a new one:");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/add.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        list.setModel(listModel);
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        scrollPaneList.setViewportView(list);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/zooper/becuz/restmote/ui/images/16/delete.png"))); // NOI18N
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    	listModel.insertElementAt(create(), 0);
        list.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
    	 int selectedIndex = list.getSelectedIndex();
         if (evt.getValueIsAdjusting() == false) {
             btnDelete.setEnabled(selectedIndex > -1);
         }
         Persistable p = selectedIndex == -1 ? null : listModel.getElementAt(selectedIndex);
         edit(p);
    }//GEN-LAST:event_listValueChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel lbl;
    private javax.swing.JList list;
    private javax.swing.JScrollPane scrollPaneList;
    // End of variables declaration//GEN-END:variables
}
